using Mailings.Web.Exceptions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Razor.TagHelpers;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mailings.Web.TagHelpers;
/// <summary>
///     Navigation section tag helper
/// </summary>
[HtmlTargetElement(ElementTag, Attributes = "action, controller")]
public sealed class NavigationSectionTagHelper : TagHelper
{
    /// <summary>
    ///     Element tag
    /// </summary>
    public const string ElementTag = "navsec";
    /// <summary>
    ///     Element class
    /// </summary>
    public const string ElementClass = "navigation-section";

    /// <summary>
    ///     Url helper factory for links generation
    /// </summary>
    private readonly IUrlHelperFactory _urlHelperFactory;

    /// <summary>
    ///     View context for creating a tag helper
    /// </summary>
    [NotMapped]
    [ViewContext]
    public ViewContext ViewContext { get; set; } = null!;

    /// <summary>
    ///     Action to which button will be redirect
    /// </summary>
    public string Action { get; set; } = null!;
    /// <summary>
    ///     Controller to which button will be redirect
    /// </summary>
    public string Controller { get; set; } = null!;
    /// <summary>
    ///     Route data
    /// </summary>
    public object? Data { get; set; } = null;

    public NavigationSectionTagHelper(IUrlHelperFactory urlHelperFactory)
    {
        _urlHelperFactory = urlHelperFactory;
    }

    /// <summary>
    ///     Processing and generation a navigation tag helper
    /// </summary>
    /// <param name="context">
    ///     Context of tag helpers
    /// </param>
    /// <param name="output">
    ///     Output of tag helpers
    /// </param>
    /// <returns>
    ///     Task of async operation by generation a navigation
    /// </returns>
    /// <exception cref="UrlIsNotGeneratedException">
    ///     Occurred when url is not generated by current action and controller
    /// </exception>
    public override async Task ProcessAsync(
        TagHelperContext context,
        TagHelperOutput output)
    {
        await base.ProcessAsync(context, output);

        var urlHelper = _urlHelperFactory.GetUrlHelper(new ActionContext(
            actionDescriptor:ViewContext.ActionDescriptor,
            httpContext: ViewContext.HttpContext,
            routeData: ViewContext.RouteData,
            modelState: ViewContext.ModelState));

        var url = urlHelper.Action(Action, Controller, Data) ?? 
                  throw new UrlIsNotGeneratedException();

        output.TagName = "a";
        output.TagMode = TagMode.StartTagAndEndTag;
        output.Attributes.Add("class", ElementClass);
        output.Attributes.Add("href", url);
    }
}